### ISSUE TITLE
Add linux compatibility to AppCreationScripts ( using Az.Resources instead ??? )

### ISSUE THREAD

**Issue by ghost** [Azure-Samples/ms-identity-javascript-nodejs-console#5]
### This issue is for a: 
```
- [] bug report -
- [X ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> $ Connect-AzureAD
### Any log messages given by the failure
>Connect-AzureAD: The term 'Connect-AzureAD' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

>Could not load file or assembly 'System.Windows.Forms`

> ...

### Expected/desired behavior
> Linux compatibility

### OS and version?
> Fedora Linux 35

### Other details that might be useful

> Link to AzAd cmdlet https://docs.microsoft.com/en-us/powershell/module/az.resources/get-azadapplication?view=azps-6.2.1

> Thanks! and happy new Year 2022! :)

**Comment by salman90** [comment]
In the backlog, please let us know if you have any more questions
