### ISSUE TITLE
401 after default configuration

### ISSUE THREAD

**Issue by Peeet93** [Azure-Samples/ms-identity-javascript-nodejs-console#8]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce

1. Clone Repo
2. npm i
3. create app at portal.azure.com (multi organization)
5. give app permission "User.Read.All"
6. create secret
7. insert secret and client id
8. node . --op getUsers

>

### Any log messages given by the failure
<img width="697" alt="image" src="https://user-images.githubusercontent.com/9379390/211912608-56d12c54-4b4f-4309-9238-015ff751b3fc.png">

>

### Expected/desired behavior
expect listing of users
>

### OS and version?
macOs 13.0.1
>

### Versions
>

### Mention any other details that might be useful
i added a console.log in index.js line 24

**Comment by salman90** [comment]
@Peeet93 interesting, I have yet to try the multi-tenant approach in this scenario. I will give the sample a run and get back to you as soon as possible.

**Comment by Peeet93** [comment]
Did you use single tenant for Testing?
I would bei fine If it works with it

**Comment by salman90** [comment]
@Peeet93 the sample works fine for the single-tenant scenario. If you're still interested in the multi-tenant approach, You will need an admin consent to provision the tenant to create a [service principa](https://learn.microsoft.com/en-us/azure/active-directory/develop/active-directory-how-applications-are-added)l for the application. You can do so by sending a request to the admin consent endpoint; take a look at this [article ](https://learn.microsoft.com/en-us/azure/active-directory/develop/v2-admin-consent)for more information. You will also need to provide the tenant-id in the configuration file. Unfortunately, the app is currently not designed to serve the multi-tenant case.

**Comment by Peeet93** [comment]
Ah thanks, my first tries with single tenant did not work, but not it is working.
Thanks for your help.

**Comment by salman90** [comment]
@Peeet93 No worries, Thanks for reaching out.
