### ISSUE TITLE
The nodejs console application fails to obtain an AD token while a similar .NET app does not

### ISSUE THREAD

**Issue by Arash-Sabet** [Azure-Samples/ms-identity-javascript-nodejs-console#9]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
I have the following configuration in place (the actual values are masked) in a .NET 6.0 console application that obtains AD tokens successfully:

```json
"Tenant": "MASKED", //this is the same as tenantId
"ClientSecret": "MASKED",
"Scope": "api://MASKED/.default",
"Instance": "https://login.microsoftonline.com/{0}",
"ClientId": "MASKED"
```

The C# code (a console/daemon app) that acquires the token successfully as per the following code snippet:

```csharp
var app = ConfidentialClientApplicationBuilder.Create(ClientId)
                .WithClientSecret(ClientSecret)
                .WithAuthority(new Uri(GetAuthority()))
                .Build();
            var scopes = new string[] { Scope };
            try
            {
                var result = await app.AcquireTokenForClient(scopes).ExecuteAsync(cancellationToken);
                response.Result = result.AccessToken;
            }
            catch (MsalServiceException mex) when (mex.Message.Contains("AADSTS70011"))
            {
                _logger.LogError(mex, $"The scope provided is not supported. {mex.Message}");
            }

GetAuthority() => string.Format(CultureInfo.InvariantCulture, Instance!, Tenant);
```

I am using the same parameters in the provided nodejs console application, but I get the following error message. Not sure whether or not it's related to using a scope as `api://MASKED/.default`. 

If I use the scope as the graph's URL, the token will be acquired successfully, but the validation code in the backed won't recognize the token as a valid one due to the scope inconsistency.

### Any log messages given by the failure

> AADSTS900023: Specified tenant identifier 'MASKED' is neither a valid DNS name, nor a valid external domain.

### Expected/desired behavior

The nodejs app should acquire a token successfully, or if a point regarding the scopes like `api://MASKED/.default` is missing in the document, that must be elaborated.

### OS and version?

OS: MacOS 13.1 on MacBook Pro M1

### Versions

Node version: 18.2.1

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by Arash-Sabet** [comment]
@salman90 Do you happen to have any inputs for this issue? Thanks.

**Comment by salman90** [comment]
@Arash-Sabet Can you please share your MSAL configuration for the node console app.

**Comment by Arash-Sabet** [comment]
@salman90 It is exactly the same as the one already shared above. Not sure what else should I share? I cannot disclose the actual ids here:

```json
"Tenant": "MASKED", //this is the same as tenantId
"ClientSecret": "MASKED",
"Scope": "api://MASKED/.default",
"Instance": "https://login.microsoftonline.com/{0}",
"ClientId": "MASKED"
```
Could you please elaborate?

**Comment by salman90** [comment]
@Arash-Sabet Share your .env file and hide the values. I need to make sure that the app is configured correctly.

**Comment by Arash-Sabet** [comment]
@salman90 I made some modifications to the way that the application would work. I translated the example to typescript and was able to get a token for the graph API. I do not have that very .env file you are looking for. But I can assure you that the configuration is 100% adequate.

**Comment by Arash-Sabet** [comment]
@salman90 Anyways, this is my test configuration:

```typescript
 const msalConfig = new MsalConfig();
    msalConfig.auth = new Auth();
    msalConfig.auth.scope = 'api://MASKED/.default';
    msalConfig.auth.aadEndPoint = 'https://login.microsoftonline.com/';
    msalConfig.auth.tenant = 'MASKED';
    msalConfig.auth.clientSecret = 'MASKED';
    msalConfig.auth.clientId = 'MASKED';
    msalConfig.auth.graphEndPoint = 'https://graph.microsoft.com/';
```

**Comment by Arash-Sabet** [comment]
@salman90 The only significant difference is that I used the scope which is 'api://MASKED/.default' in the following configuration:

```typescript
        const tokenRequest = {
            //scopes: [msalConfig.auth!.graphEndPoint + '.default']
            scopes: [msalConfig.auth!.scope]
        };
```

**Comment by salman90** [comment]
@Arash-Sabet, I need to be able to reproduce your issue to tell anything. For that, I need the code snippet containing the instantiation of msal (which involves configuration object) and how the acquireToken is called. I tried running the sample to call an API with the current setup, and I didn't manage to reproduce this error.

**Comment by Arash-Sabet** [comment]
@salman90 Understood. I will give you access to a private repository containing the code and a JEST test file. I will exclude the Azure AD configurations in that repo so that you can use yours. I will prepare that repo on this weekend.

**Comment by Arash-Sabet** [comment]
@salman90 I sent you an invitation to the repo that I just created. Please feel free to accept it. Thanks.

**Comment by salman90** [comment]
@Arash-Sabet  thanks for sharing the code. The issue is in the msal configuration options; you're passing options that do not exist in msal.js (`aadEndPoint`, `graphEndPoint`, `tenant`, `scope`). Your configuration options should look like the following:

```javascript 
  msalConfig.auth.authority = 'https://login.microsoftonline.com/' + your-tenant-id;
  msalConfig.auth.clientSecret = 'Your-app-secret';
  msalConfig.auth.clientId = 'Your-app-id`
```
Check [initializing the ConfidentialClientApplication](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-node/docs/initialize-confidential-client-application.md#initializing-the-confidentialclientapplication-object) doc for more details. You should pass the scopes in the request object on the token acquisition, not in the msal configuration object:

```javascript
const tokenRequest = {
          scopes: ['api://your-API-ID/.default'],
        };
 const token = await cca.acquireTokenByClientCredential(tokenRequest);
```

**Comment by Arash-Sabet** [comment]
@salman90 Thanks for looking into the issue. Let me try your advice later tonight, and I will keep you posted on the results. Have a great weekend.

**Comment by Arash-Sabet** [comment]
@salman90 I reviewed your inputs, and I have to say that the typescript code is correct despite those options that do not exist in msal.js (`aadEndPoint`, `graphEndPoint`, `tenant`, `scope`). I added those options  to the definition of `Auth` class to have an intuitive code, and the msal.js library should ignore the entries that it does not use and instead pick up the ones only needed.

```typescript
export class Auth {
    public clientId!: string;
    public clientSecret!: string;
    public tenant!: string;
    public aadEndPoint!: string;
    public graphEndPoint!: string;
    public scope!: string;

    public get authority(): string {
        return `${this.aadEndPoint}${this.tenant}`;
    }
}
```

Therefore the following code must pick up and use `authority`, `clientSecret` and `clientId` from the data structure above, and everything else is presumably discarded:

```typescript
const cca = new msal.ConfidentialClientApplication(msalConfig);
```

If you look at the `test` class under `src\__test__` folder, you will also realize that the `scopes` array was initialized properly like the format of `api://your-api-id/.default` because the `auth.scope` was populated per the expected pattern.

To make a story short, the configuration I shared in the repo is correct in the `typescript` world. 

Did you have a chance to use your Azure AD configuration options in the `test.ts` file and run the test to see the outcome?

**Comment by salman90** [comment]
@Arash-Sabet  I did run your test to get an access token. When you run your test the `msalConfig` object value is:

```typescript
 MsalConfig {                                                       
      auth: Auth {
        scope: 'api://11223344-abcd-1234-abcd-1234567890/.default',    
        aadEndPoint: 'https://login.microsoftonline.com/',
        tenant: 'abcdef12-aaaa-bbbb-1234-a1a1a1a1a1a1',
        clientSecret: 'aGh7Q~Mq183abcxxxvvwww',
        clientId: '12345678-1234-1111-227c-c12323444',
        graphEndPoint: 'https://graph.microsoft.com/'
      }
    }
```
You don't have an `authority` property in the configuration object. It's not advisable to add additional configurations that are not used by msal. Please revise your code again.

**Comment by Arash-Sabet** [comment]
@salman90 certainly, I will revise it later on, but we already have `authority` as a 'get' property withing `msalconfig.auth` object per the following snippet.

```typescript
public get authority(): string
```
What causes it not to be picked up?

**Comment by salman90** [comment]
@Arash-Sabet  In the Auth class, the authority is a [getter ](https://www.typescripttutorial.net/typescript-tutorial/typescript-getters-setters/)method, not an attribute of the class.

**Comment by Arash-Sabet** [comment]
Truly appreciate your help @salman90. I reconfigured the application and it started working.
